id: IA4B7C029
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:01:54.226646+00:00
last_modified: 2022-12-14 18:01:54.226649+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-088-009
  eft-text-version: 1.1.9 2021
  title: Toh_515-Dharani_of_Buddha's_Essence-v2
bases:
  F6FC:
    source_metadata: null
    order: 1
    base_file: F6FC.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
